---
title: "25-Figure3-051821"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
```

# Load packages
```{r message=FALSE, warning=FALSE, tags=c()}
#library(tidyverse)
if (!require('remotes')){
install.packages('remotes', repos='http://cran.us.r-project.org')}
if (!require('tidyverse')) {
   remotes::install_version("tidyverse", version = "1.3.0", repos = "http://cran.us.r-project.org")
   library(tidyverse)
}
if (!require('glue')) {
   remotes::install_version("glue", version = "1.4.1", repos = "http://cran.us.r-project.org")
   library(glue)
}
if (!require('cowplot')) {
   remotes::install_version("cowplot", version = "1.0.0", repos = "http://cran.us.r-project.org")
   library(cowplot)
}
if (!require('ggpubr')) {
   remotes::install_version('foreign',version="0.8-72", repos = "http://cran.us.r-project.org")
   remotes::install_version("ggpubr", version = "0.4.0", repos = "http://cran.us.r-project.org")
   library(ggpubr)
}
if (!require('ggsignif')) {
   remotes::install_version("ggsignif", version = "0.6.0", repos = "http://cran.us.r-project.org")
   library(ggsignif)
}
if (!require('RColorBrewer')) {
   remotes::install_version("RColorBrewer", version = "0.6.0", repos = "http://cran.us.r-project.org")
   library(RColorBrewer)
}
col <- brewer.pal(n = 9, name = "Set1")
sensor_colors <- brewer.pal(n = 12, name = "Set3")
effector_colors <- col[7:9] # brewer.pal(n=3, name= "Set1_r")
if(!require("FSA")){
  remotes::install_github('droglenc/FSA')
}
```

```{r include=FALSE, eval=FALSE}
# sessionInfo()
# smake<-setClass("smake",slots=list(input="list"))
# snakemake <- new("smake",input=list("sensor_connectivity_df"="../data/interim/sensor_connectivity_df.csv", "pcc_df"='../data/interim/pcc_df.csv',"sensors_pcc"="../data/interim/sensors_df.csv",'effector_pcc'='../data/interim/effectors_df.csv',
# "rwr_row"="../data/interim/rwr_ranked_goa_rows.csv","prs_row"="../data/interim/prs_ranked_goa_rows.csv",
# "rwr_column"="../data/interim/rwr_ranked_goa_columns.csv","prs_column"="../data/interim/prs_ranked_goa_columns.csv"))
```
# Load necessary data
```{r}

sensor_connectivity_df <- read_csv(snakemake@input[['sensor_connectivity_df']])#"../data/interim/sensor_connectivity_df.csv") 
pcc_df <- read_csv(snakemake@input[['pcc_df']])#'../data/interim/pcc_df.csv')
sensors_pcc <- read_csv(snakemake@input[['sensors_pcc']])%>%#'../data/interim/sensors_df.csv')%>%
 mutate(go_group = (as.character(go_group)), go_group = ifelse(go_group == "NULL", NA, go_group))
effector_pcc <- read_csv(snakemake@input[['effector_pcc']])#'../data/interim/effectors_df.csv')


```
# Figure3
## A
```{r}
sensor_neighbor_degree_plot <- pcc_df %>%
  mutate(is_sensor = factor(ifelse(sens > quantile(sens, 0.99), TRUE, FALSE), levels = c(TRUE, FALSE))) %>%
  ggplot(aes(x = is_sensor, y = log(neighbor_degree))) +
  geom_boxplot() +
  theme_bw() +
  ylab("Log(Average neighbor degree)") +
  xlab("") +
  stat_compare_means() +
  scale_x_discrete(labels = c("Sensor", "Not Sensor"))
  sensor_neighbor_degree_plot

```

## B
```{r}
sensor_connectivity_plot <-
  ggplot() +
  geom_density(data = sensor_connectivity_df %>% filter(type != "real"), aes(x = ratio, color = type)) +
  geom_vline(data = sensor_connectivity_df %>% filter(type == "real"), aes(xintercept = ratio, color = type)) +
  guides(color = guide_legend(title = "Data type"), shape = guide_legend(title = "Network type")) +
  ylab("Density") +
  xlab("% of between group edges\nto all edges") +
  theme_bw() +
  scale_color_discrete(labels = c("Random sampled set", "Sensors")) +
  theme(legend.position = "right") +
  scale_y_continuous(expand = c(0, 0))
  sensor_connectivity_plot
```

```{r}
(1/10001)<0.0001
```

## D
```{r}
# sensors_pcc$go_group <- as.factor(sensors_pcc$go_group)%>%fct_recode(
#   `Iron ion transport`  = "cellular response to iron ion starvation",
#   `Mitochondria nucleus\nsignaling pathway\nand\nTricarboxylic acid cycle`="mitochondria-nucleus signaling pathway",
#   `Phenylalanine transport`="phenylalanine transport",
#   `Hexose metabolic process`="hexose metabolic process",
#   `Tricarboxylic acid cycle`="tricarboxylic acid cycle"
# )

# sensors_sens_pval <- FSA::dunnTest(sens ~ go_group, sensors_pcc)
# sensors_sens_pval$res[sensors_sens_pval$res$P.adj < 0.1, ]
```

```{r}
sensors_pcc<- sensors_pcc%>%
    mutate(sensor_cluster=factor(replace_na(as.character(sensor_cluster),"Unclustered")),
    sensor_cluster = fct_reorder(sensor_cluster, sens))%>%
    group_by(sensor_cluster)%>%
    mutate(gid = cur_group_id())%>%ungroup()%>%
    mutate(cluster_or_go = ifelse(sensor_cluster=='Unclustered','Unclustered',
                                  ifelse(is.na(as.character(go_group)), gid, as.character(go_group))))%>%
    mutate(cluster_or_go = fct_recode(as.factor(cluster_or_go), `Iron ion\ntransport`  = "cellular response to iron ion starvation",
`Mitochondria nucleus\nsignaling pathway`="mitochondria-nucleus signaling pathway",
`Phenylalanine\ntransport`="phenylalanine transport",
`Hexose metabolic\nprocess`="hexose metabolic process",
`Tricarboxylic acid\ncycle`="tricarboxylic acid cycle"))%>%
    mutate(label = as.factor(case_when(
        cluster_or_go == 'Unclustered' ~ '\nUnclustered',
       # is.na(as.numeric(as.character(cluster_or_go))) == FALSE ~ paste0('SC',(gid-1)),
        TRUE ~ paste0('SC',gid-1)
    )))
```

```{r}
sensors_sens_pval <- FSA::dunnTest(sens ~ as.factor(label), sensors_pcc)
sensors_sens_pval$res[sensors_sens_pval$res$P.adj < 0.1, ]
```

```{r}
sensors_pcc %>% drop_na()%>%kruskal.test(deg~label,data=.)

#sensors_pcc$go_group <- as.factor(sensors_pcc$go_group)
sens_deg_comp <- ggplot(sensors_pcc %>% right_join(pcc_df)%>% 
                        mutate(label = factor(replace_na(as.character(label),"\nNon-sensor\ngenes")),
                               label=fct_reorder(label, sens),
                               label=fct_relevel(label,'\nNon-sensor\ngenes',after=Inf)), 
                        aes(x = as.factor(label), y = deg, fill = as.factor(label))) +
  geom_boxplot(
    outlier.shape=NA) +
  xlab("") +
  ylab("Degree") +
  scale_fill_manual(values = c(sensor_colors[1:10],'black')) +
  ggpubr::stat_compare_means(method = "kruskal.test", label.x.npc = .3, size=3, vjust = 1.5) +
  theme_bw() +
  theme(
        axis.title.y=element_text(size=14),
        axis.text.y=element_text(size=10),
        axis.text.x = element_text(size=7), 
        legend.title = element_blank(),
    legend.text = element_text(margin = margin(t = 10, b = 10))
  )+scale_y_log10()
sens_deg_comp

```

## E
```{r}
#comparisons[order(sapply(comparisons, function(x) x[1], simplify=TRUE), decreasing=TRUE)]
```

```{r}
comparisons <- str_split(sensors_sens_pval$res[sensors_sens_pval$res$P.adj < 0.1, ]$Comparison,' - ',2)

if(nrow(sensors_pcc%>%drop_na(go_group))!=0){
sens_sens_comp <- ggplot(sensors_pcc %>% mutate(label = fct_reorder(label, sens)) %>%
  mutate(sens_norm = sens / 5183), aes(x = (label), y = sens_norm, fill =(label))) +
  geom_boxplot() +
  geom_signif(
    comparisons = comparisons[order(sapply(comparisons, function(x) x[1], simplify=TRUE), decreasing=TRUE)],
    annotation = c("***","*" , "*" ,  "***"), y_position = c(0.007, 0.005,0.0058, 0.0078),
                                           textsize = 3#, 0.008)
  ) +
  xlab("") +
  ylab("Sensitivity (a.u.)") +
  scale_fill_manual(values = sensor_colors) +
  theme_bw() +
  theme(
        axis.title.y=element_text(size=14),
        axis.text.y=element_text(size=10),
        axis.text.x = element_text(size=7),
        legend.title = element_blank())+
        ylim(NA, 0.008)

sens_sens_comp}
```

# Figure4
## A
```{r}
eff_neighbor_degree_plot <- pcc_df %>%
  mutate(sens_norm = sens / nrow(.), eff_norm = eff / nrow(.), group = "real")%>%
  mutate(is_effector = factor(ifelse(eff_norm > quantile(eff_norm, 0.99), TRUE, FALSE), levels = c(TRUE, FALSE))) %>%
  ggplot(aes(x = is_effector, y = log(neighbor_degree))) +
  geom_boxplot() +
  theme_bw() +
  ylab("Log(Average neighbor degree)") +
  xlab("") +
  stat_compare_means() +
  scale_x_discrete(labels = c("Effector", "Not Effector"))
eff_neighbor_degree_plot
```

## C
```{r}
# effector_pcc$go_group <- as.factor(effector_pcc$go_group)%>%fct_recode(
#   golgi = "phosphatidylinositol biosynthetic process",
#   mito = "mitochondrial cytochrome c oxidase assembly",
#   chromosome = "replication fork protection"
# )
effector_pcc  <- effector_pcc%>%mutate(go_group=fct_reorder(go_group, eff))
# res.aov <- kruskal.test(deg~go_group, data= effector_pcc)
# res.aov
effector_eff_pval <- FSA::dunnTest(eff ~ go_group, effector_pcc)
effector_eff_pval$res[effector_eff_pval$res$P.adj < 0.1, ]
effector_deg_pval <- FSA::dunnTest(deg ~ go_group, effector_pcc)
effector_deg_pval$res[effector_deg_pval$res$P.adj < 0.1, ]

comparisons_effectors <- str_split(effector_deg_pval$res$Comparison,' - ',2)

eff_deg_comp <- ggplot(effector_pcc %>% right_join(pcc_df)%>% 
                       mutate(go_group = factor(replace_na(as.character(go_group),"Others")),
                              go_group=fct_reorder(go_group, eff),
                              go_group= fct_relevel(go_group,'Others',after=Inf)), 
                       aes(x = go_group, y = deg, fill = go_group)) +
  geom_boxplot(outlier.shape = NA) +
   scale_fill_manual(
     values = c(effector_colors,'black'),
     labels = c("EC1 (Chromosome\nSegregation)", "EC2 (Golgi vesicle\nTransport)", "EC3 (Respiratory complex\nassembly)",'Non-effector genes')
   ) +
    scale_x_discrete(labels=c('EC1','EC2','EC3','Non-effector\ngenes'))+
  xlab("") +
  ylab("Degree") +
  theme_bw() +
   geom_signif(
     comparisons = comparisons_effectors[order(sapply(comparisons_effectors, function(x) x[1], simplify=TRUE), decreasing=TRUE)], #list(c("golgi", "chromosome"), c("golgi", "mito"), c("mito", "chromosome")),
     annotation = c("*", "***", "ns"),
     y_position = c(115, 120, 130)
   ) +
  theme(
       axis.text.y=element_text(size=10),
        axis.title.y=element_text(size=14),legend.title = element_blank(), legend.text = element_text(margin = margin(t = 10, b = 10))) # , legend.spacing.y = unit(2,'in'))+
eff_deg_comp
```

## D
```{r}

eff_eff_comp <- ggplot(effector_pcc %>% #mutate(go_group = fct_reorder(go_group, eff)) %>%
  mutate(eff_norm = eff / 5183), aes(x = go_group, y = eff_norm, fill = go_group)) +
  geom_boxplot() +
  xlab("") +
  ggpubr::stat_compare_means(method = "kruskal.test") +
   scale_fill_manual(values = effector_colors,
   labels = c("EC1 (Chromosome\nSegregation)", "EC2 (Golgi vesicle\nTransport)", "EC3 (Respiratory complex\nassembly)")) +
  ylab("Effectiveness (a.u.)") +
    scale_x_discrete(labels=c('EC1','EC2','EC3','Non-effector\ngenes'))+

  theme_bw() +
  theme(
        axis.text.y=element_text(size=10),
        axis.title.y=element_text(size=14), legend.title = element_blank())
eff_eff_comp
```


```{r}
#if(snakemake@params['save']==TRUE){
  figure_folder = "../reports/figures/paper_figures_052521/"
ggsave(glue("{figure_folder}/fig3a.png"),plot=sensor_neighbor_degree_plot,width=3,height=3)
ggsave(glue("{figure_folder}/fig3b.png"),plot=sensor_connectivity_plot,width=3.5,height=2.5)
ggsave(glue("{figure_folder}/fig3d.png"),plot=sens_deg_comp+theme(legend.position='none'),width=3.9,height=2.1)
ggsave(glue("{figure_folder}/fig3e.png"),plot=sens_sens_comp+theme(legend.position='none'),width=3.9,height=2.1)


ggsave(glue("{figure_folder}/fig4a.png"),plot=eff_neighbor_degree_plot,width=3,height=3)
ggsave(glue("{figure_folder}/fig4c.png"),plot=eff_deg_comp+theme(legend.position='none'),width=3,height=3)
ggsave(glue("{figure_folder}/fig4d.png"),plot=eff_eff_comp+theme(legend.position='none'),width=3,height=3)



# Using the cowplot package
legend <- cowplot::get_legend(sens_deg_comp+theme(legend.position='bottom',
legend.key.height = unit(2, 'cm')))
        
        #guides(fill = guide_legend(override.aes = list(size = 5))))
legend_plot <- ggdraw(legend)
ggsave(glue("{figure_folder}/fig3d_legend.pdf"),plot=legend_plot, width=10, height=2)
#}
```

```{r}

```
